name: Next.js Frontend CI

on:
  push:
    branches: ['main']
    paths:
      - 'akkuea-edu/packages/nextjs/**'
      - '.github/workflows/akkuea-edu/nextjs.yml'
  pull_request:
    branches: ['main']
    paths:
      - 'akkuea-edu/packages/nextjs/**'
      - '.github/workflows/akkuea-edu/nextjs.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            akkuea-edu/packages/nextjs/node_modules
          key: ${{ runner.os }}-nextjs-bun-${{ hashFiles('akkuea-edu/packages/nextjs/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-bun-

      - name: Install dependencies
        run: bun install
        working-directory: akkuea-edu/packages/nextjs

      - name: Lint code
        run: bun run lint
        working-directory: akkuea-edu/packages/nextjs

      - name: Build application
        run: bun run build
        working-directory: akkuea-edu/packages/nextjs
